services:
  db:
    image: postgres:15
    container_name: wfm-postgres
    environment:
      - POSTGRES_DB=odoo_local
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:19.0
    container_name: wfm-odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ../addons:/mnt/extra-addons
      - ./odoo-local.conf:/etc/odoo/odoo.conf:ro
    restart: unless-stopped

volumes:
  odoo-data:
  postgres-data:
