services:
  odoo:
    image: odoo:19.0
    container_name: wfm-odoo-local
    ports:
      - "8069:8069"
    volumes:
      - odoo-local-data:/var/lib/odoo
      - ../addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: wfm-postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgres-local-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  odoo-local-data:
  postgres-local-data:
