services:
  odoo:
    image: odoo:19.0
    container_name: wfm-odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ../addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    environment:
      - HOST=178.128.200.45
      - USER=odoo_user
      - PASSWORD=OdooAdmin2025
    restart: unless-stopped

volumes:
  odoo-data:
